name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint src/
        run: flake8 src/ --max-line-length=120 --ignore=E265,E501,E702,F401

      - name: Lint tests
        run: flake8 tests/ --max-line-length=120 --ignore=E265,E501,E702,F401

      - name: Format check src/
        run: black --check src/

      - name: Format check tests/
        run: black --check tests/

      - name: Run tests
        run: pytest

      - name: Run main script tests
        run: pytest --maxfail=1 --cov=src --cov-report=term-missing

      - name: Run tests with coverage
        run: |
          pytest --cov
          coverage report --skip-covered --format=markdown | tee coverage.md
          coverage html
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          path: coverage.md

      - name: Display coverage in GitHub summary
        run: cat coverage.md >> $GITHUB_STEP_SUMMARY